#!/bin/sh
# Copyright 2026 edcsnt. All rights reserved.

case $1 in -l) w=0; shift; esac
case $# in
[01]) printf 'usage: offset [-l] file function...\n' >&2; exit 1
esac

f=$1
shift
export LC_ALL=C

case $w in
?*)
	for fn
	do : $((${#fn}>w && (w=${#fn})))
	done
esac

for fn
do
	case $w in
	?*)
		pre=$fn' '
		while :
		do
			case $((${#pre} > w)) in 1) break; esac
			pre=$pre' '
		done
	esac
	case $fn in
	*[\&*./[\\]*)
		esc=
		while :
		do
			c=${fn%"${fn#?}"}
			fn=${fn#?}
			case $c in
			        '') break        ;;
			[\&*./[\\]) esc=$esc\\$c ;;
			         *) esc=$esc$c
			esac
		done
		;;
	*)
		esc=$fn
	esac
	s="$s;s/^$esc [iTtWw] \([^ ]*\).*/${pre}0x\1/p"
done

nm -P "$f" | sed -n "${s#;}"
